### ISSUE TITLE
BVH traversal speed benchmarking

### ISSUE THREAD

**Issue by Enigmatisms** [Niravaana/HIP-BVH-Construction#2]
Hi! This is a great repo, thanks for this work. Yet I wonder whether you have benchmarked traversal speed of different BVH algorithms. I used a simple linear SAH BVH (stackless) in my own CUDA path tracing renderer, and I wish to know whether there is any way to push forward the performance. Maybe we can have some discussions on this topic (GPU BVH traversal efficiency) if you have benchmarked some. If you haven't and currently have no intention for this, this issue can just be closed. 

Thanks again! Starred, really good repo.

**Comment by Niravaana** [comment]
Hey 
Thanks a lot. Glad you find it useful. 
Yes I am in process of implementing multiple traversal methods. 
I have not formally done performance comparisons yet, though surely we can have discussion on this. 
So far I have implemented if/if, while/while, speculative while/while and restart trail traversals.
These are for Binary bvh so far I will need to update them for wide bvh.
Next one is persistent thread based speculative while/while. I think after this I will have enough material to do formal perf comparisons and publish some stuff.
