### ISSUE TITLE
Q: Other primitives?

### ISSUE THREAD

**Issue by ib00** [Niravaana/HIP-BVH-Construction#3]
Cool project.

How hard would it be to add arbitrary primitives?

It seems that building BVH would not require huge changes (as long as you have AABB, index and primitive type tag),
but traversal would seem to be messy because you have a potential divergence problem. 

This is something that I often see swept under the rug (ie, everybody just assumes triangles). It would be good to see
a fairly performant traversal kernel for arbitrary primitives.

How would you tackle this? Two obvious ways are:
1) Call intersection function in the traversal inner loop (divergence problem if you have different primitives)
2) Combine leaf primitives by type and then call each intersection function

Thoughts?

**Comment by Niravaana** [comment]
I think building one BLAS for each primitive type and combining it with speculative while while like traversal algorithm will be the best option. Which is I think option 2 you are referring to here.

**Comment by ib00** [comment]
I was actually thinking about building one BLAS, but just before intersecting leaves, reorder rays per primitive-type.
I was thinking that maybe persistent threads approach may work here.

**Comment by Niravaana** [comment]
yeah that also sounds good too.
