### ISSUE TITLE
Inclusion of `math.h` in Kernels?

### ISSUE THREAD

**Issue by peanutrino** [Niravaana/HIP-BVH-Construction#4]
Hi! Thanks for this amaaazing project! 😊

I’m currently writing my thesis, and we’d love to use the `hploc` code in our project, but I’ve run into an issue with the inclusion of `math.h` in the kernels. From what I understand, standard library headers like `math.h` aren’t typically compatible with runtime JIT compilation, but it seems you’ve managed to include it successfully, and I am wondering how— is this something Orochi related?

Here’s the error I’m encountering at runtime:

```
1 catastrophic error detected in the compilation of "CalculateMortonCodes".
Compilation terminated.
Orochi error invalid resource handle on line 158 in file ..\src\Kernel.cpp
Orochi error invalid resource handle on line 127 in file ..\src\Kernel.cpp
Orochi error invalid resource handle on line 128 in file ..\src\Kernel.cpp
../../src/Common.h(23): catastrophic error: cannot open source file "math.h"
  #include <math.h>
                   ^
```

Am I missing something? 

All of this is very new to me so any help would be much appreciated.
Thank you in advance!

**Comment by Niravaana** [comment]
Hey 

Thanks alot and glad you find the project useful.

You can add following define 

```  
     #if ( defined( __CUDACC__ ) || defined( __HIPCC__ ) ) 
     #define __KERNELCC__
     #endif
   
     #if !defined (__KERNELCC__)
     #include <math.h>
     #endif
```

__HIPCC__ is a define which HIP compiler adds for you, this is defined inside kernel. So you can add your own define __KERNELCC__ to know device side code(kernel) and host side code. 
So with code I provided above you can have a header file that you can include in both host and device code and math.h will be included only in the host code and you will not get that error. As the error suggests that HIP is trying to compile the kernel file and it finds include statement for math.h which it doesnt understand.

another thing you can try is take look at 

https://github.com/Niravaana/HIP-BVH-Construction/blob/58a6502be2224a2ee2199e4e40c1de715cb3f4ba/src/Kernel.cpp#L52

and send options to compilation for example  "options.push_back("-std=c++17");"

Hope this helps.
Shoot me message if you need any help with this.

Regards,
X

**Comment by peanutrino** [comment]
Hi!

Thank you so much for your help and explanation—it worked perfectly! 😊

I’ve run into a few other issues and was hoping you might be able to help. I’ve sent you an email with the details—thank you in advance for taking a look!

Best,
Iman

**Comment by Niravaana** [comment]
Cool, lets continue conversation on the email thread. I will close this issue.
